import { format } from 'date-fns';

export interface LegalDocumentData {
  title: string;
  type: string;
  date: string;
  content: Record<string, string>;
  parties?: {
    applicant?: string;
    respondent?: string;
  };
}

export const generatePDFContent = (data: LegalDocumentData): string => {
  let content = '';

  content += `
═══════════════════════════════════════════════════════════════
                         ${data.title.toUpperCase()}
═══════════════════════════════════════════════════════════════

Date: ${format(new Date(data.date), 'dd MMMM yyyy')}
Type: ${data.type}

`;

  switch (data.type) {
    case 'FIR':
      content += generateFIRContent(data.content);
      break;
    case 'NOTICE':
      content += generateNoticeContent(data.content);
      break;
    case 'AFFIDAVIT':
      content += generateAffidavitContent(data.content);
      break;
    case 'AGREEMENT':
      content += generateAgreementContent(data.content);
      break;
    case 'PETITION':
      content += generatePetitionContent(data.content);
      break;
    case 'WILL':
      content += generateWillContent(data.content);
      break;
    default:
      content += generateGenericContent(data.content);
  }

  content += `

═══════════════════════════════════════════════════════════════
                         DECLARATION
═══════════════════════════════════════════════════════════════

I, the undersigned, hereby declare that the above information
is true and correct to the best of my knowledge and belief.

_______________________________
Signature / Thumb Impression

Date: _________________________

═══════════════════════════════════════════════════════════════
                    IMPORTANT DISCLAIMER
═══════════════════════════════════════════════════════════════

This document is generated by LexAI for informational purposes
only. It does NOT constitute legal advice and should NOT be
treated as a legally binding document without verification by
a qualified legal professional.

For any legal proceedings, please consult a licensed advocate.

© LexAI - AI-Powered Legal Assistant
═══════════════════════════════════════════════════════════════
`;

  return content;
};

function generateFIRContent(content: Record<string, string>): string {
  return `
FIRST INFORMATION REPORT (FIR)
Under Section 154, Criminal Procedure Code, 1973

Police Station: ${content.policeStation || 'N/A'}
District: ${content.district || 'N/A'}

COMPLAINANT DETAILS:
Name: ${content.complainantName || 'N/A'}
Father's/Husband's Name: ${content.fatherName || 'N/A'}
Address: ${content.complainantAddress || 'N/A'}
Contact: ${content.complainantContact || 'N/A'}

ACCUSED DETAILS (if known):
Name: ${content.accusedName || 'Not Known'}
Address: ${content.accusedAddress || 'Not Known'}

DATE, TIME & PLACE OF OCCURRENCE:
Date: ${content.incidentDate || 'N/A'}
Time: ${content.incidentTime || 'N/A'}
Place: ${content.incidentPlace || 'N/A'}

FACTS OF THE CASE:
${content.description || 'N/A'}

OFFENCE(S) COMMITTED:
${content.offences || 'N/A'}

RELIEF SOUGHT:
${content.relief || 'N/A'}
`;
}

function generateNoticeContent(content: Record<string, string>): string {
  return `
LEGAL NOTICE
Under Section 80, Code of Civil Procedure, 1908

FROM:
${content.senderName || 'N/A'}
${content.senderAddress || 'N/A'}

TO:
${content.receiverName || 'N/A'}
${content.receiverAddress || 'N/A'}

Date: ${content.noticeDate || 'N/A'}
Subject: ${content.subject || 'N/A'}

Dear Sir/Madam,

${content.body || 'N/A'}

RELIEF CLAIMED:
${content.relief || 'N/A'}

TIME TO COMPLY: You are hereby given 30 days from the date of 
receipt of this notice to rectify the above-mentioned matter.

FAILURE TO COMPLY will result in legal proceedings without 
further notice.

_______________________________
 Advocate / Sender
`;
}

function generateAffidavitContent(content: Record<string, string>): string {
  return `
AFFIDAVIT
(To be sworn before an Oath Commissioner or Notary Public)

I, ${content.declarantName || 'N/A'}, son/daughter/wife of ${content.fatherName || 'N/A'}, 
aged ${content.age || 'N/A'}, residing at ${content.address || 'N/A'}, do hereby 
solemnly affirm and declare as follows:

${content.declaration || 'N/A'}

The contents of this affidavit are true and correct to the best 
of my knowledge and belief.

DEPONENT

Verified at ${content.verificationPlace || 'N/A'} on this ${content.verificationDate || 'N/A'} day.

_______________________________
DEPONENT

IDENTITY VERIFIED:
_______________________________
Oath Commissioner / Notary Public
`;
}

function generateAgreementContent(content: Record<string, string>): string {
  return `
AGREEMENT
${content.agreementType || 'General Agreement'}

This Agreement is made on ${content.agreementDate || 'N/A'} at ${content.place || 'N/A'}

BETWEEN:

Party A: ${content.partyAName || 'N/A'}
Address: ${content.partyAAddress || 'N/A'}
(hereinafter referred to as "First Party")

AND

Party B: ${content.partyBName || 'N/A'}
Address: ${content.partyBAddress || 'N/A'}
(hereinafter referred to as "Second Party")

WHEREAS:
${content.whereas || 'N/A'}

NOW THIS AGREEMENT WITNESSETH:
${content.terms || 'N/A'}

CONSIDERATION: Rs. ${content.consideration || 'N/A'}/-

DURATION: ${content.duration || 'N/A'}

WITNESSES:
1. _____________________________
2. _____________________________

_______________________________
(First Party)

_______________________________
(Second Party)
`;
}

function generatePetitionContent(content: Record<string, string>): string {
  return `
PETITION / APPLICATION
Before the Hon'ble ${content.court || 'Court'}

IN THE MATTER OF:
${content.petitionerName || 'N/A'}
......Petitioner(s)

 versus

${content.respondentName || 'N/A'}
......Respondent(s)

PETITION UNDER: ${content.petitionUnder || 'N/A'}

RESPECTFULLY SHOWETH:

1. ${content.grounds || 'N/A'}

RELIEF SOUGHT:
${content.relief || 'N/A'}

PETITIONER(S)
Through: ${content.advocateName || 'N/A'}
Advocate
`;
}

function generateWillContent(content: Record<string, string>): string {
  return `
LAST WILL AND TESTAMENT
of
${content.testatorName || 'N/A'}

I, ${content.testatorName || 'N/A'}, son/daughter of ${content.fatherName || 'N/A'}, 
aged ${content.age || 'N/A'}, residing at ${content.address || 'N/A'}, being of 
sound mind and disposing memory, do hereby make, publish and declare 
this to be my Last Will and Testament:

ARTICLE 1 - DECLARATION:
I declare that I have not made any former Will.

ARTICLE 2 - FAMILY DETAILS:
Spouse: ${content.spouseName || 'N/A'}
Children: ${content.childrenDetails || 'N/A'}

ARTICLE 3 - EXECUTORS:
I appoint ${content.executorName || 'N/A'} as the Executor of this Will.

ARTICLE 4 - SPECIFIC BEQUESTS:
${content.bequests || 'N/A'}

ARTICLE 5 - RESIDUARY CLAUSE:
All the rest and residue of my estate shall be distributed to ${content.residuary || 'N/A'}

IN WITNESS WHEREOF, I have set my hand to this Will on ${content.date || 'N/A'}

_______________________________
( Testator Signature )

SIGNED AND DECLARED by the above-named Testator as the Testator's
Last Will and Testament in our presence:

Witness 1: _____________________________
Address: _____________________________

Witness 2: _____________________________
Address: _____________________________
`;
}

function generateGenericContent(content: Record<string, string>): string {
  let result = 'DOCUMENT DETAILS:\n\n';
  for (const [key, value] of Object.entries(content)) {
    result += `${key}: ${value}\n`;
  }
  return result;
}
