export const DOCUMENT_TEMPLATES = [
  {
    id: 'fir',
    name: 'First Information Report (FIR)',
    description: 'File a complaint with the police about a crime',
    category: 'Criminal',
    icon: 'FileText',
    fields: [
      { name: 'policeStation', label: 'Police Station', type: 'text', required: true, placeholder: 'Enter police station name' },
      { name: 'district', label: 'District', type: 'text', required: true, placeholder: 'Enter district' },
      { name: 'complainantName', label: 'Your Full Name', type: 'text', required: true, placeholder: 'Enter your full name' },
      { name: 'fatherName', label: "Father's/Husband's Name", type: 'text', required: true, placeholder: "Enter father's or husband's name" },
      { name: 'complainantAddress', label: 'Your Address', type: 'textarea', required: true, placeholder: 'Enter your complete address' },
      { name: 'complainantContact', label: 'Contact Number', type: 'text', required: false, placeholder: 'Enter phone number' },
      { name: 'accusedName', label: "Accused's Name (if known)", type: 'text', required: false, placeholder: "Enter accused's name or 'Not Known'" },
      { name: 'accusedAddress', label: "Accused's Address", type: 'text', required: false, placeholder: "Enter accused's address" },
      { name: 'incidentDate', label: 'Date of Incident', type: 'date', required: true },
      { name: 'incidentTime', label: 'Time of Incident', type: 'text', required: false, placeholder: 'e.g., 10:30 AM' },
      { name: 'incidentPlace', label: 'Place of Incident', type: 'text', required: true, placeholder: 'Enter exact location' },
      { name: 'description', label: 'Describe the Incident', type: 'textarea', required: true, placeholder: 'Describe what happened in detail' },
      { name: 'offences', label: 'Likely Offences (IPC Sections)', type: 'textarea', required: false, placeholder: 'e.g., Theft under Section 379 IPC' },
      { name: 'relief', label: 'Relief Sought', type: 'textarea', required: false, placeholder: 'What action do you want the police to take?' },
    ],
  },
  {
    id: 'notice',
    name: 'Legal Notice',
    description: 'Send a formal legal notice before filing a case',
    category: 'Civil',
    icon: 'Mail',
    fields: [
      { name: 'senderName', label: 'Your Full Name/Company Name', type: 'text', required: true, placeholder: 'Enter your name' },
      { name: 'senderAddress', label: 'Your Address', type: 'textarea', required: true, placeholder: 'Enter your complete address' },
      { name: 'receiverName', label: 'Recipient Name/Company', type: 'text', required: true, placeholder: 'To whom the notice is addressed' },
      { name: 'receiverAddress', label: 'Recipient Address', type: 'textarea', required: true, placeholder: "Recipient's complete address" },
      { name: 'noticeDate', label: 'Date of Notice', type: 'date', required: true },
      { name: 'subject', label: 'Subject', type: 'text', required: true, placeholder: 'Brief subject of the notice' },
      { name: 'body', label: 'Notice Content', type: 'textarea', required: true, placeholder: 'Describe the matter and what you want the recipient to do' },
      { name: 'relief', label: 'Relief Claimed', type: 'textarea', required: false, placeholder: 'What are you demanding?' },
    ],
  },
  {
    id: 'affidavit',
    name: 'Affidavit',
    description: 'A written statement confirmed by oath for court proceedings',
    category: 'General',
    icon: 'Scroll',
    fields: [
      { name: 'declarantName', label: 'Declarant Name', type: 'text', required: true, placeholder: 'Full legal name' },
      { name: 'fatherName', label: "Father's Name", type: 'text', required: true, placeholder: "Father's full name" },
      { name: 'age', label: 'Age', type: 'text', required: true, placeholder: 'Enter age' },
      { name: 'address', label: 'Current Address', type: 'textarea', required: true, placeholder: 'Complete residential address' },
      { name: 'declaration', label: 'Declaration Statement', type: 'textarea', required: true, placeholder: 'State the facts you are declaring' },
      { name: 'verificationPlace', label: 'Place of Verification', type: 'text', required: true, placeholder: 'City where signing' },
      { name: 'verificationDate', label: 'Date of Verification', type: 'date', required: true },
    ],
  },
  {
    id: 'agreement',
    name: 'Agreement',
    description: 'Draft a legal agreement between two parties',
    category: 'Civil',
    icon: 'FileSignature',
    fields: [
      { name: 'agreementType', label: 'Type of Agreement', type: 'text', required: true, placeholder: 'e.g., Rental Agreement, Sale Deed' },
      { name: 'agreementDate', label: 'Date of Agreement', type: 'date', required: true },
      { name: 'place', label: 'Place of Agreement', type: 'text', required: true, placeholder: 'City' },
      { name: 'partyAName', label: 'First Party Name', type: 'text', required: true, placeholder: 'Full name or company name' },
      { name: 'partyAAddress', label: 'First Party Address', type: 'textarea', required: true },
      { name: 'partyBName', label: 'Second Party Name', type: 'text', required: true, placeholder: 'Full name or company name' },
      { name: 'partyBAddress', label: 'Second Party Address', type: 'textarea', required: true },
      { name: 'whereas', label: 'Background (Whereas Clause)', type: 'textarea', required: true, placeholder: 'Context and purpose of agreement' },
      { name: 'terms', label: 'Terms and Conditions', type: 'textarea', required: true, placeholder: 'Detailed terms of the agreement' },
      { name: 'consideration', label: 'Consideration Amount (₹)', type: 'text', required: false, placeholder: 'e.g., 100000' },
      { name: 'duration', label: 'Duration/Term Period', type: 'text', required: false, placeholder: 'e.g., 11 months, 5 years' },
    ],
  },
  {
    id: 'petition',
    name: 'Petition/Application',
    description: 'Draft a petition or application for court filing',
    category: 'Court',
    icon: 'Scale',
    fields: [
      { name: 'court', label: 'Name of Court', type: 'text', required: true, placeholder: 'e.g., Honble High Court of Delhi' },
      { name: 'petitionerName', label: 'Petitioner Name', type: 'text', required: true },
      { name: 'respondentName', label: 'Respondent Name', type: 'text', required: true },
      { name: 'petitionUnder', label: 'Petition Under', type: 'text', required: true, placeholder: 'e.g., Section 34 of Hindu Marriage Act' },
      { name: 'grounds', label: 'Grounds of Petition', type: 'textarea', required: true, placeholder: 'Detailed grounds for the petition' },
      { name: 'relief', label: 'Relief Sought', type: 'textarea', required: true, placeholder: 'What order are you seeking?' },
      { name: 'advocateName', label: 'Advocate Name (if any)', type: 'text', required: false, placeholder: 'Your advocate name' },
    ],
  },
  {
    id: 'will',
    name: 'Last Will & Testament',
    description: 'Draft your last will and testament',
    category: 'Estate',
    icon: 'BookOpen',
    fields: [
      { name: 'testatorName', label: 'Your Full Name', type: 'text', required: true },
      { name: 'fatherName', label: "Father's Name", type: 'text', required: true },
      { name: 'age', label: 'Age', type: 'text', required: true },
      { name: 'address', label: 'Current Address', type: 'textarea', required: true },
      { name: 'spouseName', label: 'Spouse Name', type: 'text', required: false },
      { name: 'childrenDetails', label: 'Children Details', type: 'textarea', required: false, placeholder: 'Names and ages of children' },
      { name: 'executorName', label: 'Executor Name', type: 'text', required: true, placeholder: 'Person who will execute the will' },
      { name: 'bequests', label: 'Specific Bequests (Gifts)', type: 'textarea', required: false, placeholder: 'List specific items and who should receive them' },
      { name: 'residuary', label: 'Residuary Beneficiary', type: 'text', required: false, placeholder: 'Who should get remaining assets?' },
      { name: 'date', label: 'Date of Will', type: 'date', required: true },
    ],
  },
] as const;

export type TemplateId = typeof DOCUMENT_TEMPLATES[number]['id'];
